name: Wheel build

# Controls when the workflow will run
on: [push]

jobs:
  build-wheel:
    name: Build ${{ matrix.platform }} wheels
    runs-on: ubuntu-latest
    strategy:    
      matrix:
        platform:
          #- manylinux1_x86_64
          #- manylinux1_i686
          - manylinux2014_x86_64
          - manylinux2014_aarch64          
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Build manylinux Python wheels
      uses: RalfG/python-wheels-manylinux-build@v0.3.4-${{ matrix.platform }}
      with:
        python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38 cp39-cp39'
        build-requirements: 'numpy pyyaml nomkl pytest'
    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist        
